"""add payment_status to orders

Revision ID: 1df44e74c7ed
Revises: 75216b4748bf
Create Date: 2026-01-21 11:50:06.510208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1df44e74c7ed'
down_revision: Union[str, Sequence[str], None] = '75216b4748bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.alter_column('payments', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
