"""paypal paymeny

Revision ID: 4ca132394efd
Revises: fb868a136d22
Create Date: 2026-02-27 12:49:26.620970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca132394efd'
down_revision: Union[str, Sequence[str], None] = 'fb868a136d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paypal_capture_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_orders_paypal_capture_id'), 'orders', ['paypal_capture_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_paypal_capture_id'), table_name='orders')
    op.drop_column('orders', 'paypal_capture_id')
    # ### end Alembic commands ###
