"""payment provider statuses

Revision ID: 75216b4748bf
Revises: b4f93d36d86a
Create Date: 2026-01-21 11:48:49.137040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75216b4748bf'
down_revision: Union[str, Sequence[str], None] = 'b4f93d36d86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_message_type', sa.String(length=64), nullable=True))
    op.add_column('payments', sa.Column('provider_order_status', sa.String(length=64), nullable=True))
    op.add_column('payments', sa.Column('provider_invoice_status', sa.String(length=64), nullable=True))
    op.add_column('payments', sa.Column('provider_approve_status', sa.String(length=64), nullable=True))
    op.add_column('payments', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'raw_payload')
    op.drop_column('payments', 'provider_approve_status')
    op.drop_column('payments', 'provider_invoice_status')
    op.drop_column('payments', 'provider_order_status')
    op.drop_column('payments', 'provider_message_type')
    # ### end Alembic commands ###
