"""ordeк_email_confirm

Revision ID: aa2f41111c38
Revises: f845bd8ea970
Create Date: 2026-01-28 20:25:42.566960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2f41111c38'
down_revision: Union[str, Sequence[str], None] = 'f845bd8ea970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) добавляем confirmation_email_sent_at (просто поле)
    op.add_column(
        "orders",
        sa.Column("confirmation_email_sent_at", sa.DateTime(timezone=True), nullable=True),
    )

    # 2) добавляем need_post_process с временным дефолтом, чтобы не упасть на NOT NULL
    op.add_column(
        "orders",
        sa.Column(
            "need_post_process",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )

    # 3) ГЛАВНОЕ: гарантируем, что ВСЕ старые заказы не будут обработаны
    op.execute("UPDATE orders SET need_post_process = false")

    # 4) (необязательно, но правильно) убираем server_default,
    # чтобы БД сама не проставляла, а ты контролировал это в коде
    op.alter_column("orders", "need_post_process", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'need_post_process')
    op.drop_column('orders', 'confirmation_email_sent_at')
    # ### end Alembic commands ###
