"""add checkout fields to orders

Revision ID: aca980b66068
Revises: d195ed4a2214
Create Date: 2026-01-20 11:27:21.406744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aca980b66068'
down_revision: Union[str, Sequence[str], None] = 'd195ed4a2214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_email', sa.String(length=320), nullable=True))
    op.add_column('orders', sa.Column('customer_name', sa.String(length=200), nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=40), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_orders_customer_email'), 'orders', ['customer_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_customer_email'), table_name='orders')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'customer_email')
    # ### end Alembic commands ###
