"""add tracking_nr

Revision ID: d0ae79b7364c
Revises: 214aaddc1b12
Create Date: 2026-01-27 14:24:45.059359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ae79b7364c'
down_revision: Union[str, Sequence[str], None] = '214aaddc1b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    op.drop_column('orders', 'tracking_number')
    # ### end Alembic commands ###
