"""discount added

Revision ID: d7c952be2d62
Revises: 9866b176f075
Create Date: 2026-01-31 12:49:27.849311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c952be2d62'
down_revision: Union[str, Sequence[str], None] = '9866b176f075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) discount_amount: NOT NULL + server_default
    op.add_column(
        "orders",
        sa.Column("discount_amount", sa.Numeric(12, 2), nullable=False, server_default="0.00"),
    )

    # 2) discount_reason: nullable
    op.add_column(
        "orders",
        sa.Column("discount_reason", sa.Text(), nullable=True),
    )

    # 3) подстраховка: если вдруг где-то окажутся NULL
    op.execute("UPDATE orders SET discount_amount = 0.00 WHERE discount_amount IS NULL")

    # 4) (не обязательно) убрать server_default, если хочешь чтобы только ORM задавал
    # Я бы оставил, но вот как убрать:
    # op.alter_column("orders", "discount_amount", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount_reason')
    op.drop_column('orders', 'discount_amount')
    # ### end Alembic commands ###
