"""order_number

Revision ID: e1a6a12cc074
Revises: d0ae79b7364c
Create Date: 2026-01-28 10:08:56.353599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.models.order import generate_smart_order_number

# revision identifiers, used by Alembic.
revision: str = 'e1a6a12cc074'
down_revision: Union[str, Sequence[str], None] = 'd0ae79b7364c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Создаем колонку, разрешая временный NULL
    op.add_column('orders', sa.Column('order_number', sa.String(length=12), nullable=True))

    # 2. Наполняем данными существующие записи
    connection = op.get_bind()
    metadata = sa.MetaData()
    orders_table = sa.Table('orders', metadata, autoload_with=connection)

    all_orders = connection.execute(sa.select(orders_table.c.id)).fetchall()

    for order in all_orders:
        new_number = generate_smart_order_number()
        connection.execute(
            orders_table.update()
            .where(orders_table.c.id == order.id)
            .values(order_number=new_number)
        )

    # 3. Устанавливаем ограничение NOT NULL, когда данных уже нет пустыми
    op.alter_column('orders', 'order_number', nullable=False)

    # 4. Создаем уникальный индекс
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###
