"""order_number1

Revision ID: f845bd8ea970
Revises: e1a6a12cc074
Create Date: 2026-01-28 10:36:12.699035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f845bd8ea970'
down_revision: Union[str, Sequence[str], None] = 'e1a6a12cc074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###
